# Generated by Django 4.1.1 on 2022-10-04 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(max_length=500)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='main_app.character')),
            ],
        ),
    ]
