# Generated by Django 4.1.1 on 2022-10-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('quotes', models.ManyToManyField(to='main_app.quote')),
            ],
        ),
    ]
